// Generated by gencpp from file sam_hub/SAMcmdMsg.msg
// DO NOT EDIT!


#ifndef SAM_HUB_MESSAGE_SAMCMDMSG_H
#define SAM_HUB_MESSAGE_SAMCMDMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sam_hub
{
template <class ContainerAllocator>
struct SAMcmdMsg_
{
  typedef SAMcmdMsg_<ContainerAllocator> Type;

  SAMcmdMsg_()
    : command(0)  {
    }
  SAMcmdMsg_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::sam_hub::SAMcmdMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_hub::SAMcmdMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SAMcmdMsg_

typedef ::sam_hub::SAMcmdMsg_<std::allocator<void> > SAMcmdMsg;

typedef boost::shared_ptr< ::sam_hub::SAMcmdMsg > SAMcmdMsgPtr;
typedef boost::shared_ptr< ::sam_hub::SAMcmdMsg const> SAMcmdMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_hub::SAMcmdMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sam_hub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sam_hub': ['/home/nhattan/catkin_ws/src/sam_hub/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMcmdMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMcmdMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMcmdMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36e1d21d1340e2a5e93f075b6457cbdf";
  }

  static const char* value(const ::sam_hub::SAMcmdMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36e1d21d1340e2a5ULL;
  static const uint64_t static_value2 = 0xe93f075b6457cbdfULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_hub/SAMcmdMsg";
  }

  static const char* value(const ::sam_hub::SAMcmdMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 command\n\
";
  }

  static const char* value(const ::sam_hub::SAMcmdMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SAMcmdMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_hub::SAMcmdMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_hub::SAMcmdMsg_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_HUB_MESSAGE_SAMCMDMSG_H
