// Generated by gencpp from file sam_hub/SAMJointPos12Msg.msg
// DO NOT EDIT!


#ifndef SAM_HUB_MESSAGE_SAMJOINTPOS12MSG_H
#define SAM_HUB_MESSAGE_SAMJOINTPOS12MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sam_hub
{
template <class ContainerAllocator>
struct SAMJointPos12Msg_
{
  typedef SAMJointPos12Msg_<ContainerAllocator> Type;

  SAMJointPos12Msg_()
    : SAMMode()
    , SAMPos12()  {
      SAMMode.assign(0);

      SAMPos12.assign(0);
  }
  SAMJointPos12Msg_(const ContainerAllocator& _alloc)
    : SAMMode()
    , SAMPos12()  {
  (void)_alloc;
      SAMMode.assign(0);

      SAMPos12.assign(0);
  }



   typedef boost::array<uint8_t, 25>  _SAMMode_type;
  _SAMMode_type SAMMode;

   typedef boost::array<uint16_t, 25>  _SAMPos12_type;
  _SAMPos12_type SAMPos12;




  typedef boost::shared_ptr< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> const> ConstPtr;

}; // struct SAMJointPos12Msg_

typedef ::sam_hub::SAMJointPos12Msg_<std::allocator<void> > SAMJointPos12Msg;

typedef boost::shared_ptr< ::sam_hub::SAMJointPos12Msg > SAMJointPos12MsgPtr;
typedef boost::shared_ptr< ::sam_hub::SAMJointPos12Msg const> SAMJointPos12MsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sam_hub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sam_hub': ['/home/nhattan/catkin_ws/src/sam_hub/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "367ce2d6abdd6aa34db1dc123aa9b6d1";
  }

  static const char* value(const ::sam_hub::SAMJointPos12Msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x367ce2d6abdd6aa3ULL;
  static const uint64_t static_value2 = 0x4db1dc123aa9b6d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_hub/SAMJointPos12Msg";
  }

  static const char* value(const ::sam_hub::SAMJointPos12Msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[25] SAMMode\n\
uint16[25] SAMPos12\n\
";
  }

  static const char* value(const ::sam_hub::SAMJointPos12Msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SAMMode);
      stream.next(m.SAMPos12);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SAMJointPos12Msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_hub::SAMJointPos12Msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_hub::SAMJointPos12Msg_<ContainerAllocator>& v)
  {
    s << indent << "SAMMode[]" << std::endl;
    for (size_t i = 0; i < v.SAMMode.size(); ++i)
    {
      s << indent << "  SAMMode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.SAMMode[i]);
    }
    s << indent << "SAMPos12[]" << std::endl;
    for (size_t i = 0; i < v.SAMPos12.size(); ++i)
    {
      s << indent << "  SAMPos12[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.SAMPos12[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_HUB_MESSAGE_SAMJOINTPOS12MSG_H
