// Generated by gencpp from file sam_hub/SAMJointStateMsg.msg
// DO NOT EDIT!


#ifndef SAM_HUB_MESSAGE_SAMJOINTSTATEMSG_H
#define SAM_HUB_MESSAGE_SAMJOINTSTATEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sam_hub
{
template <class ContainerAllocator>
struct SAMJointStateMsg_
{
  typedef SAMJointStateMsg_<ContainerAllocator> Type;

  SAMJointStateMsg_()
    : SAMPos12Avail()
    , SAMPos12()  {
      SAMPos12Avail.assign(0);

      SAMPos12.assign(0);
  }
  SAMJointStateMsg_(const ContainerAllocator& _alloc)
    : SAMPos12Avail()
    , SAMPos12()  {
  (void)_alloc;
      SAMPos12Avail.assign(0);

      SAMPos12.assign(0);
  }



   typedef boost::array<uint8_t, 25>  _SAMPos12Avail_type;
  _SAMPos12Avail_type SAMPos12Avail;

   typedef boost::array<uint16_t, 25>  _SAMPos12_type;
  _SAMPos12_type SAMPos12;




  typedef boost::shared_ptr< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> const> ConstPtr;

}; // struct SAMJointStateMsg_

typedef ::sam_hub::SAMJointStateMsg_<std::allocator<void> > SAMJointStateMsg;

typedef boost::shared_ptr< ::sam_hub::SAMJointStateMsg > SAMJointStateMsgPtr;
typedef boost::shared_ptr< ::sam_hub::SAMJointStateMsg const> SAMJointStateMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sam_hub::SAMJointStateMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sam_hub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sam_hub': ['/home/nhattan/catkin_ws/src/sam_hub/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee07b202ad4d497497e892512fa2ff47";
  }

  static const char* value(const ::sam_hub::SAMJointStateMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee07b202ad4d4974ULL;
  static const uint64_t static_value2 = 0x97e892512fa2ff47ULL;
};

template<class ContainerAllocator>
struct DataType< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sam_hub/SAMJointStateMsg";
  }

  static const char* value(const ::sam_hub::SAMJointStateMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[25] SAMPos12Avail\n\
uint16[25] SAMPos12\n\
";
  }

  static const char* value(const ::sam_hub::SAMJointStateMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SAMPos12Avail);
      stream.next(m.SAMPos12);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SAMJointStateMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sam_hub::SAMJointStateMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sam_hub::SAMJointStateMsg_<ContainerAllocator>& v)
  {
    s << indent << "SAMPos12Avail[]" << std::endl;
    for (size_t i = 0; i < v.SAMPos12Avail.size(); ++i)
    {
      s << indent << "  SAMPos12Avail[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.SAMPos12Avail[i]);
    }
    s << indent << "SAMPos12[]" << std::endl;
    for (size_t i = 0; i < v.SAMPos12.size(); ++i)
    {
      s << indent << "  SAMPos12[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.SAMPos12[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAM_HUB_MESSAGE_SAMJOINTSTATEMSG_H
